import {
  CONTROL_DATA_PROPS_TYPES,
  CONTROL_PROPS_TYPES,
  FILE_DATA_PROPS_TYPES,
  LAYOUT_CONTROL_PROPS_TYPES,
} from '../../utils/control-props-types';

export const propertiesStore = {
  [CONTROL_PROPS_TYPES.LABEL]: {
    name: 'label',
    title: 'Label',
    type: 'string',
    placeholder: 'Enter a label',
    required: true,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.PLACEHOLDER]: {
    name: 'placeholder',
    title: 'Placeholder',
    type: 'string',
    placeholder: 'Enter a placeholder',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.CUSTOM_CLASS]: {
    name: 'customClass',
    title: 'Custom Class',
    type: 'string',
    placeholder: 'Custom CSS classes',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.DESCRIPTION]: {
    name: 'description',
    title: 'Description',
    type: 'html',
    placeholder: 'Enter a description',
    required: false,
    options: undefined,
    value: '',
    className: 'code-editor-xsmall',
  },
  [CONTROL_PROPS_TYPES.TOOLTIP]: {
    name: 'tooltip',
    title: 'Tooltip',
    type: 'html',
    placeholder: 'Enter a tooltip',
    required: false,
    options: undefined,
    value: '',
    className: 'code-editor-xsmall',
  },
  [CONTROL_PROPS_TYPES.PREFIX]: {
    name: 'prefix',
    title: 'Prefix',
    type: 'string',
    placeholder: 'Enter a prefix',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.SUFFIX]: {
    name: 'suffix',
    title: 'Suffix',
    type: 'string',
    placeholder: 'Enter a suffix',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.TAB_INDEX]: {
    name: 'tabIndex',
    title: 'Tab Index',
    type: 'number',
    placeholder: 'Enter a tabIndex',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.HIDDEN]: {
    name: 'hidden',
    title: 'Hidden',
    type: 'boolean',
    placeholder: 'Enter a hidden',
    required: false,
    options: undefined,
    value: false,
  },
  [CONTROL_PROPS_TYPES.DISABLED]: {
    name: 'disabled',
    title: 'Disabled',
    type: 'boolean',
    placeholder: 'Enter a disabled',
    required: false,
    options: undefined,
    value: false,
  },
  [CONTROL_PROPS_TYPES.HIDE_LABEL]: {
    name: 'hideLabel',
    title: 'Hide Label',
    type: 'boolean',
    placeholder: 'Enter a hideLabel',
    required: false,
    options: undefined,
    value: false,
  },
  [CONTROL_PROPS_TYPES.CHECKED]: {
    name: 'checked',
    title: 'Checked',
    type: 'boolean',
    placeholder: 'Enter a checked',
    required: false,
    options: undefined,
    value: false,
  },
  [CONTROL_PROPS_TYPES.TEXTAREA_ROWS]: {
    name: 'rows',
    title: 'Size',
    type: 'select',
    placeholder: 'Select a size',
    required: false,
    options: [
      { value: 1, text: 'Single' },
      { value: 3, text: 'Medium' },
      { value: 5, text: 'Large' },
    ],
    value: '',
  },

  [CONTROL_PROPS_TYPES.ACTION]: {
    // Options are submit, reset, button
    name: 'action',
    title: 'Action',

    type: 'select',
    placeholder: 'Select an action',
    required: false,
    options: [
      { value: 'submit', text: 'Submit' },
      { value: 'reset', text: 'Reset' },
      { value: 'button', text: 'Button' },
    ],
    value: 'submit',
  },
  [CONTROL_PROPS_TYPES.SAVE_ON_ENTER]: {
    name: 'checked',
    title: 'Save on enter',
    type: 'boolean',
    placeholder: 'Enter a checked',
    required: false,
    options: undefined,
    value: false,
  },
  [CONTROL_PROPS_TYPES.THEME]: {
    // it's a select with values default, primary, secondary, success, danger, warning, info, light, dark
    name: 'theme',
    title: 'Theme',
    type: 'select',
    placeholder: 'Select a theme',
    required: false,
    options: [
      { value: 'default', text: 'Default' },
      { value: 'primary', text: 'Primary' },
      { value: 'secondary', text: 'Secondary' },
      { value: 'success', text: 'Success' },
      { value: 'danger', text: 'Danger' },
      { value: 'warning', text: 'Warning' },
      { value: 'info', text: 'Info' },
      { value: 'light', text: 'Light' },
      { value: 'dark', text: 'Dark' },
      { value: 'link', text: 'Link' },
    ],
    value: '',
  },
  [CONTROL_PROPS_TYPES.SIZE]: {
    // it's a select with values sm, lg
    name: 'size',
    title: 'Size',
    type: 'select',
    placeholder: 'Select a size',
    required: false,
    options: [
      { value: '', text: 'Normal' },
      { value: 'btn-sm', text: 'Small' },
      { value: 'btn-lg', text: 'Large' },
    ],
    value: '',
  },
  [CONTROL_PROPS_TYPES.BLOCK_BUTTON]: {
    name: 'blockButton',
    title: 'Block button',
    type: 'boolean',
    placeholder: 'Enter a blockButton',
    required: false,
    options: undefined,
    value: false,
  },
  [CONTROL_PROPS_TYPES.LEFT_ICON]: {
    name: 'leftIcon',
    title: 'Left icon',
    type: 'string',
    placeholder: 'e.g. bi bi-icon',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.RIGHT_ICON]: {
    name: 'rightIcon',
    title: 'Right icon',
    type: 'string',
    placeholder: 'e.g. bi bi-icon',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.DISPLAY_MASK]: {
    name: 'displayMask',
    title: 'Display Mask',
    type: 'string',
    placeholder: 'Enter a display mask',
    required: false,
    options: undefined,
  },

  [LAYOUT_CONTROL_PROPS_TYPES.TAG]: {
    name: 'tag',
    title: 'HTML tag',
    type: 'string',
    placeholder: 'Enter a HTML tag',
    required: false,
    options: undefined,
    value: '',
  },
  [LAYOUT_CONTROL_PROPS_TYPES.HTML_CONTENT]: {
    name: 'htmlContent',
    title: 'Content',
    type: 'html',
    placeholder: 'Enter any HTML',
    required: false,
    options: undefined,
    value: '',
    className: 'code-editor-small',
  },
  [CONTROL_DATA_PROPS_TYPES.ITEM_TEMPLATE]: {
    name: 'itemTemplate',
    title: 'Item Template',
    type: 'html',
    placeholder: 'Enter an item template',
    required: false,
    options: undefined,
    value: '<span>{{ item.name }}</span>',
    className: 'code-editor-xsmall',
  },
  [FILE_DATA_PROPS_TYPES.MULTIPLE_FILES]: {
    name: 'multipleFiles',
    title: 'Allow multiple files',
    type: 'boolean',
    required: false,
    value: false,
  },
  [FILE_DATA_PROPS_TYPES.DISPLAY_AS_IMAGES]: {
    name: 'displayAsImages',
    title: 'Display as image(s)',
    type: 'boolean',
    required: false,
    options: undefined,
    value: false,
  },
  [FILE_DATA_PROPS_TYPES.FILE_MAX_SIZE]: {
    name: 'fileMaxSize',
    title: 'File maximum size',
    type: 'text',
    required: false,
    options: undefined,
    value: '5MB',
  },
  [FILE_DATA_PROPS_TYPES.FILE_MIN_SIZE]: {
    name: 'fileMinSize',
    title: 'File minimum size',
    type: 'text',
    required: false,
    options: undefined,
    value: '0KB',
  },
  [FILE_DATA_PROPS_TYPES.FILE_FORMATS]: {
    name: 'fileFormats',
    title: 'Formats accepted',
    type: 'string',
    placeholder: 'e.g. .pdf, .docx, .xlsx',
    required: false,
    options: undefined,
    value: '',
  },
  [FILE_DATA_PROPS_TYPES.FILE_TYPES]: {
    name: 'fileTypes',
    title: 'File types',
    type: 'array',
    required: false,
    options: undefined,
    value: '',
    props: {
      sortable: false,
      structure: {
        label: {
          name: 'label',
          title: 'Label',
          type: 'string',
          placeholder: '',
          required: true,
          value: '',
        },
        value: {
          name: 'value',
          title: 'Value',
          type: 'string',
          placeholder: '.pdf, .docx, .xlsx',
          required: true,
          value: '',
        },
      },
    },
  },
};
