import { CONTROL_PROPS_TYPES, LAYOUT_CONTROL_PROPS_TYPES } from '../../utils/control-props-types';

export const propertiesStore = {
  [CONTROL_PROPS_TYPES.LABEL]: {
    name: 'label',
    title: 'Label',
    type: 'string',
    placeholder: 'Enter a label',
    required: true,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.PLACEHOLDER]: {
    name: 'placeholder',
    title: 'Placeholder',
    type: 'string',
    placeholder: 'Enter a placeholder',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.CUSTOM_CLASS]: {
    name: 'customClass',
    title: 'Custom Class',
    type: 'string',
    placeholder: 'Custom CSS classes',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.DESCRIPTION]: {
    name: 'description',
    title: 'Description',
    type: 'string',
    placeholder: 'Enter a description',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.TOOLTIP]: {
    name: 'tooltip',
    title: 'Tooltip',
    type: 'string',
    placeholder: 'Enter a tooltip',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.PREFIX]: {
    name: 'prefix',
    title: 'Prefix',
    type: 'string',
    placeholder: 'Enter a prefix',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.SUFFIX]: {
    name: 'suffix',
    title: 'Suffix',
    type: 'string',
    placeholder: 'Enter a suffix',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.TAB_INDEX]: {
    name: 'tabIndex',
    title: 'Tab Index',
    type: 'number',
    placeholder: 'Enter a tabIndex',
    required: false,
    options: undefined,
    value: '',
  },
  [CONTROL_PROPS_TYPES.HIDDEN]: {
    name: 'hidden',
    title: 'Hidden',
    type: 'boolean',
    placeholder: 'Enter a hidden',
    required: false,
    options: undefined,
    value: false,
  },
  [CONTROL_PROPS_TYPES.DISABLED]: {
    name: 'disabled',
    title: 'Disabled',
    type: 'boolean',
    placeholder: 'Enter a disabled',
    required: false,
    options: undefined,
    value: false,
  },
  [CONTROL_PROPS_TYPES.HIDE_LABEL]: {
    name: 'hideLabel',
    title: 'Hide Label',
    type: 'boolean',
    placeholder: 'Enter a hideLabel',
    required: false,
    options: undefined,
    value: false,
  },
  [CONTROL_PROPS_TYPES.CHECKED]: {
    name: 'checked',
    title: 'Checked',
    type: 'boolean',
    placeholder: 'Enter a checked',
    required: false,
    options: undefined,
    value: false,
  },
  [CONTROL_PROPS_TYPES.MAX_DATE]: {
    name: 'max',
    title: 'Max Date',
    type: 'select',
    placeholder: 'Enter a max date',
    required: false,
    options: [],
    value: '',
  },
  [CONTROL_PROPS_TYPES.MIN_DATE]: {
    name: 'min',
    title: 'Min Date',
    type: 'select',
    placeholder: 'Set a min date',
    required: false,
    options: [],
    value: '',
  },
  [CONTROL_PROPS_TYPES.TEXTAREA_ROWS]: {
    name: 'rows',
    title: 'Size',
    type: 'select',
    placeholder: 'Select a size',
    required: false,
    options: [
      { value: 1, text: 'Single' },
      { value: 3, text: 'Medium' },
      { value: 5, text: 'Large' },
    ],
    value: '',
  },
  [LAYOUT_CONTROL_PROPS_TYPES.TAG]: {
    name: 'tag',
    title: 'HTML tag',
    type: 'string',
    placeholder: 'Enter a HTML tag',
    required: false,
    options: undefined,
    value: '',
  },
  [LAYOUT_CONTROL_PROPS_TYPES.HTML_CONTENT]: {
    name: 'htmlContent',
    title: 'Content',
    type: 'html',
    placeholder: 'Enter any HTML',
    required: false,
    options: undefined,
    value: '',
  },
};
